### PR TITLE
Hide elements if no data is available #208

### PR DESCRIPTION
**Pull request by plutonik-a**
Only show 
* search when TEI:text is available and 
* download panels when pdf/ebooks available

Fixes https://github.com/eXistSolutions/hsg-shell/issues/208

### CODE REVIEW

**Comment by plutonik-a** [comment]
#### Without `tei:text` node
[http://localhost:8080/exist/apps/hsg-shell/historicaldocuments/frus1919v01](http://localhost:8080/exist/apps/hsg-shell/historicaldocuments/frus1919v01)
bildschirmfoto 2016-05-27 um 22 17 47

#### Without media to download
[http://localhost:8080/exist/apps/hsg-shell/historicaldocuments/frus1945v01](http://localhost:8080/exist/apps/hsg-shell/historicaldocuments/frus1945v01)
bildschirmfoto 2016-05-27 um 22 17 37

#### With text and media
[https://history.state.gov/historicaldocuments/frus1952-54v01p1](https://history.state.gov/historicaldocuments/frus1952-54v01p1)
bildschirmfoto 2016-05-27 um 22 17 20

**Comment by plutonik-a** [comment]
@wolfgangmm 
Can you please test the cases in above comment, because the lack of S3 on my local machine?

**Comment by plutonik-a** [comment]
@joewiz @wolfgangmm 
This PR is ready for review and merge.
Please have a close look on the 3 test cases mentioned above https://github.com/eXistSolutions/hsg-shell/pull/236#issuecomment-222244681
(https://github.com/eXistSolutions/hsg-shell/pull/236#issuecomment-222245448)

**Comment by joewiz** [comment]
@plutonik-a Thank you, this looks great! I've redeployed hsg-shell to include these changes.

**Pull request merged**
