### PR TITLE
Part 2 of "Fix grid layout"

### PR DESCRIPTION
**Pull request by plutonik-a**
Since my previous 'work-in-progress' PR https://github.com/eXistSolutions/hsg-shell/pull/149 has already been merged, I continue my fixes in this feature-branch - also still work-in-progress!

Improvements so far:
* fluid layout on landing page
* consistent use of bootstrap grid classes on landing page, header navigation and footer
* decoupling basic and static layout styling from bootstrap by using "hsg"-prefixed, customized classes

### CODE REVIEW

**Comment by plutonik-a** [comment]
### 1200px screen width: 
Large page-margins and borders, takes up the "old" layout
min-1200px


### From 768px to 1199px width
The content stretches to full width, but without borders and colored backgrounds and still keeps large page-margins
#### Header
min-786px
---
#### Footer
footer-min-768px

**Comment by plutonik-a** [comment]
### Fixed Historical Documents Overview and new Panel
Fixes #120

panel-volumes

panel-mobile

**Comment by joewiz** [comment]
@plutonik-a Wow, this looks wonderful so far!

**Comment by plutonik-a** [comment]
### Historical Documents: Responsive Layout with Sidebar

sidebar-frus-history-research

### Fix Ebook Downloads
ebook-list-buttons

**Comment by plutonik-a** [comment]
### Main sidebar "Historical Resources" implemented on each page in historical documents:
admin-resources-sidebars

**Comment by plutonik-a** [comment]
### Sidebar on every landing and subpage in Department History:
dep-hist-sidebar

**Comment by plutonik-a** [comment]
### "Biographies" Layout and Improved Sidebar
biography-sidebar

### Countries
countries

countries-article

**Comment by plutonik-a** [comment]
### Fixed Sidebars and Arrow-Navigation in "About"-Subpages

bildschirmfoto 2016-03-28 um 18 20 07
---
bildschirmfoto 2016-03-28 um 18 20 23
---
### Mobile Layout

bildschirmfoto 2016-03-28 um 18 46 44

**Comment by plutonik-a** [comment]
Last ToDo before merge:
Apply fixed arrow navigation markup to sub-subpages.

**Comment by plutonik-a** [comment]
This PR is ready to merge.

**Pull request merged**
