### PR TITLE
WIP: Fix grid layout

### LINKED ISSUE #114: Left content margin is missing on smaller screens
On breakpoint screen width 991px, the content sticks on the left side with nearly no margin.
Also there are different alignments regarding small heading, breadcrumb, content and menu.

[http://localhost:8080/exist/apps/hsg-shell/milestones/1750-1775/foreword](http://localhost:8080/exist/apps/hsg-shell/milestones/1750-1775/foreword)

bug-17-wrong-grid-mobile

### PR DESCRIPTION
**Pull request by plutonik-a**
#### Fix responsive grid for main content on landing-page
  - Main container „Latest News“ and social sidebar are stacked on mobile devices and tablet devices. 
  - The elements within the sidebar are displayed in 2 columns only on medium wide screens like tablet portrait.

#### Apply responsive grid layout to default page template
   - Header and main element are expanding in full width on mobile and tablet (portrait) devices, but keep border and gray background on large devices.
   - The main content contains 2 columns only on large screens: main and sidebar.
   - On medium sized devices, the sidebar is displayed in 2 columns below the main content.
   - On mobile devices, all sidebar elements will be stacked in one column under the main content.

#### Create style-guide compliant footer with additional info
   - add nav element to footer
   - add navigation elements to footer
   - add contact information footer (phone, e-mail)
   - add additional topics to footer navigation
   - apply styling to footer according to US Web Standard style-guide ([https://playbook.cio.gov/designstandards/footers/#big-footer](https://playbook.cio.gov/designstandards/footers/#big-footer))

---
### Entire Front Page
entire-page
---
### Sidebar Medium Size
sidebar-medium
---
### Sidebar Mobile
sidebar-mobile
---
### Footer Medium Size
footer-medium
---
### Footer Large
footer-large

---
Fixes  #114, #116 , #120, #145, #112

### CODE REVIEW

**Comment by plutonik-a** [comment]
@joewiz 
The content of the footer is just my own suggestion. 
Please have a look, if you would like to change anything.

In milestone 2 we should provide the mobile footer navigation as a hidden accordion navigation for a better user experience and a cleaner look.

**Comment by joewiz** [comment]
@plutonik-a These changes sound and look like great improvements. Two questions:

> On medium sized devices, the sidebar is displayed in 2 columns below the main content.

What will happen in the case of a page whose sidebar only contains a single panel, e.g., http://localhost:8080/exist/apps/hsg-shell/historicaldocuments/frus1948v01p2/d4? Will this page's "Abbreviations & Terms" panel expand to the full width of the 2 columns, or will there be an empty column? The latter would not be a deal breaker. 

If these changes don't break the prev/next page navigation buttons, they sound good and pull-able to me - when you call them done.

**Comment by line-o** [comment]
@joewiz looks good to me as well.

**Comment by plutonik-a** [comment]
@joewiz 
> What will happen in the case of a page whose sidebar only contains a single panel
I would suggest, the single sidebar (panel) will expand full-width on small screens. 
The 2-column sidebar was only meant for the landing-page, because that sidebar is containing 2 sections.
NB: As this PR affected only the default template and is already merged now, I am going to continue fixing the grid / columns in a following PR.

**Comment by joewiz** [comment]
@plutonik-a Sounds like a good plan.

**Pull request merged**
